### ISSUE TITLE
New changelist format in `git-changelist-maven-extension` 1.3 breaks PCT testing of core incrementals

### ISSUE THREAD

**Issue by basil** [jenkinsci/incrementals-tools#28]
### Jenkins and plugins versions report

Jenkins: 2.329-rc31964.3b_29e9d46038 (from [this build](https://ci.jenkins.io/job/Core/job/jenkins/job/master/3221/))
OS: Ubuntu 20.04.3 LTS x86_64

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04.3 LTS x86_64

### Reproduction steps

Updating `sample-plugin/pom.xml` to

```
diff --git a/sample-plugin/pom.xml b/sample-plugin/pom.xml
index 396fceb..b996501 100644
--- a/sample-plugin/pom.xml
+++ b/sample-plugin/pom.xml
@@ -14,7 +14,7 @@
     <properties>
         <changelist>999999-SNAPSHOT</changelist>
         <bom>weekly</bom>
-        <jenkins.version>2.328</jenkins.version>
+        <jenkins.version>2.329-rc31964.3b_29e9d46038</jenkins.version>
         <java.level>8</java.level>
     </properties>
     <dependencyManagement>
```

try running e.g. `PLUGINS=mailer TEST=jenkins.plugins.mailer.tasks.MimeMessageBuilderTest\#test_send bash local-test.sh`.

### Expected Results

The test passes.

### Actual Results

The test fails with

```
Hook: org.jenkins.tools.test.hook.NodeCleanupBeforeCompileHook
Hook: org.jenkins.tools.test.hook.MultiParentCompileHook
Loaded multi-parent compile hook
Exception in thread "main" java.io.IOException: no jenkins-core.jar in /home/basil/src/jenkinsci/bom/target/local-test/megawar.war
        at org.jenkins.tools.test.PluginCompatTester.scanWAR(PluginCompatTester.java:872)
        at org.jenkins.tools.test.PluginCompatTester.testPlugins(PluginCompatTester.java:193)
        at org.jenkins.tools.test.PluginCompatTesterCli.main(PluginCompatTesterCli.java:175)
```

### Anything else?

https://github.com/jenkinsci/plugin-compat-tester/blob/5a86f00cbbbba4e2c7dcb63f75538c8765e24e96/plugins-compat-tester/src/main/java/org/jenkins/tools/test/PluginCompatTester.java#L126-L127 needs to be adjusted to match the new versioning scheme.

**Comment by jglick** [comment]
Do you want to propose a PR? I am guessing we just need to replace `[0-9a-f.]` with `[0-9a-f._]`?

**Comment by jglick** [comment]
Awkward because `bom` still relies on https://github.com/jenkinsci/plugin-compat-tester/pull/276 which I never managed to get over the line (https://github.com/jenkinsci/bom/issues/657).

**Comment by basil** [comment]
> which I never managed to get over the line

Well, in the immortal words of the great philosopher [William Edward Hickson](https://en.wikipedia.org/wiki/William_Edward_Hickson)

> If at first you don't succeed, try, try, try again.

**Comment by jglick** [comment]
Quick workaround would be a draft PR that merges the proposed fix for this with https://github.com/jenkinsci/plugin-compat-tester/pull/276, just to get an incremental build.

**Comment by jglick** [comment]
Now tracked as https://github.com/jenkinsci/plugin-compat-tester/issues/340.
