### ISSUE TITLE
`incrementals-tools` generates version numbers which are Dependabot prereleases

### ISSUE THREAD

**Issue by basil** [jenkinsci/incrementals-tools#34]
https://github.com/jenkinsci/jenkins-test-harness/releases/tag/1933.vda_8285a_2162a was not offered by Dependabot as expected. Rather it was erroneously filtered out as a prerelease by https://github.com/dependabot/dependabot-core/blob/1afa8518245f23c14eb652452e6f9539e48893d7/maven/lib/dependabot/maven/update_checker/version_finder.rb#L34. The Dependabot tokenization of this version was ["1933", "vda_8285", "a_2162", "a"]. The last token causes https://github.com/dependabot/dependabot-core/blob/1afa8518245f23c14eb652452e6f9539e48893d7/maven/lib/dependabot/maven/version.rb#L57 to erroneously flag this as an alpha version. One solution would be to append an underscore in cases like this so that the last token would be "a_" and would not trigger https://github.com/dependabot/dependabot-core/blob/1afa8518245f23c14eb652452e6f9539e48893d7/maven/lib/dependabot/maven/version.rb#L57.

**Comment by basil** [comment]
[Previously](https://github.com/jenkinsci/incrementals-tools/issues/28), [previously](https://github.com/jenkinsci/plugin-compat-tester/issues/340), [previously](https://github.com/jenkinsci/incrementals-tools/pull/24), [previously](https://github.com/jenkinsci/plugin-compat-tester/pull/341), [previously](https://github.com/jenkinsci/incrementals-tools/pull/31).

**Comment by jglick** [comment]
> Previously

FTR https://github.com/jenkinsci/incrementals-tools/issues/28 + https://github.com/jenkinsci/plugin-compat-tester/issues/340 + https://github.com/jenkinsci/incrementals-tools/pull/24 + https://github.com/jenkinsci/plugin-compat-tester/pull/341 + https://github.com/jenkinsci/incrementals-tools/pull/31

> One solution would be to append an underscore in cases like this

Reverting #31 basically (except retaining test coverage). Seems like the most prudent approach. @jetersen @timja any comment?

**Comment by basil** [comment]
To be clear, the lack of a trailing underscore is fine for any digit or letter except for "a" or "b", in which case it triggers https://github.com/dependabot/dependabot-core/blob/1afa8518245f23c14eb652452e6f9539e48893d7/maven/lib/dependabot/maven/version.rb#L57.

**Comment by jetersen** [comment]
what if we remove the last a or b at the end the commit sha will still be unique enough?

**Comment by jglick** [comment]
I am not comfortable with that. _Adding_ hex digits until you find `[0-9c-f]` would be OK (though obviously this trick would not work if your commit hash happened to be like `d9c67b3aaaaabbbbaabbbabaaabbb`).

**Comment by jglick** [comment]
Yes as per https://github.com/jenkinsci/incrementals-tools/issues/34#issuecomment-1402540011; was just waiting to see if there were any alternate ideas, since this did not appear urgent.

**Comment by basil** [comment]
Caused downstream issues: https://github.com/jenkinsci/bom/issues/1805, https://github.com/jenkinsci/bom/issues/1806, https://github.com/jenkinsci/bom/issues/1807
