### ISSUE TITLE
Pick a better parent POM

### ISSUE THREAD

**Issue by jglick** [jenkinsci/incrementals-tools#36]
`org.kohsuke:pom:19` is out of date, and even version 21 is pretty old. Seems you cannot release using JDK 11

```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project lib: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
```

`jenkinsci/pom` is not appropriate since it is not in Central.

**Comment by NotMyFault** [comment]
This is superseded since we switched to https://github.com/jenkinsci/central-repository-pom
